<?php

namespace AppBundle\Repository;

/**
 * ColiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColiRepository extends \Doctrine\ORM\EntityRepository
{
}
