<?php

namespace AppBundle\Repository;

/**
 * ImxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImxRepository extends \Doctrine\ORM\EntityRepository
{
}
